### ISSUE TITLE
General usage fixes

### ISSUE THREAD

**Issue by Westhes** [njannink/T4ForUnity#1]
Just a quick few notes which are not described in the readme.
This script only supports `TextTemplatingFileGenerator` out of the box, and does not check the editor assembly.

### Solution:
- **For editor assembly support:** replace the string ["Assembly-CSharp.csproj"](https://github.com/njannink/T4ForUnity/blob/master/src/Editor/T4TemplatePostProcessor.cs#L53) with `"Assembly-CSharp*.csproj"`.
- **For runtime text templates:** modify the content of the string from [TextTemplatingFileGenerator](https://github.com/njannink/T4ForUnity/blob/master/src/Editor/T4TemplatePostProcessor.cs#L33) to `TextTemplatingFilePreprocessor`.

**Comment by njannink** [comment]
readme updated thanks for the feedback
